development:
  adapter: postgresql
  encoding: unicode
  database: dummy_development
  pool: 5
  username: root
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: dummy_test
  pool: 5
  username: root
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: dummy_production
  pool: 5
  username: root
  password:
